---
######################################################
#
#    bootstrap main user 
#
######################################################
# README:
#     Main user for Ansible use
#

#-----------------------------------------------------
#   variablen
#
#- name: task_name | load variables 
#  tags: tag1,tag2
#  set_fact:
#    MAIN_USER: 
#    SUDO_GROUP: 
#    MAIN_USER_PASSWD: "{{ beispiel_variable }}"
#    var_4: 

#-----------------------------------------------------
#   DEBUG
#
#- name: task_name | DEBUG - show loaded variables
#  tags: tag1,tag2,debug
#  debug:
#    msg: 
#      - "{{ MAIN_USER }}"
#      - "{{ SUDO_GROUP }}"
#      - "{{ MAIN_USER_PASSWD }}"
#      - "{{ var_4 }}"


#-----------------------------------------------------
#   pre_tasks
#
- name: users | main_user | Update and upgrade package packages
  tags: users,main_user,bootstrap
  package:
    update_cache: true
    upgrade: dist
  become_user: true

- name: users | main_user | Ensure needed packages are installed
  tags: packages,users,main_user,bootstrap
  package:
    name: 
      - sudo
      - "{{ OPENSSH_PACKAGE }}"
    state: present
  become_user: true

#-----------------------------------------------------
#   Main
#

- name: users | main_user | Create user 
  tags: users,main_user,bootstrap
  user:
    name: "{{ MAIN_USER }}"
    password: "{{ MAIN_USER_PASSWD | password_hash('sha512') }}"
    comment: "Main User"
    shell: /bin/bash
    groups: "{{ SUDO_GROUP }},{{ MAIN_USER }}"
    create_home: true
    append: true
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_comment: "{{ MAIN_USER }}"
    state: present


- name: users | main_user | "sudoers.d"
  tags: users,main_user,bootstrap
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ MAIN_USER }}
    line: "{{ MAIN_USER }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    mode: '0440'


#-----------------------------------------------------
#   post_tasks
#


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#


