---
######################################################
#
#     NAME
#
######################################################
# README:
#
#

#-----------------------------------------------------
#   variablen
#
#- name: task_name | load variables 
#  tags: tag1,tag2
#  set_fact:
#    var_1: 
#    var_2: 
#    var_3: "{{ beispiel_variable }}"
#    var_4: 

#-----------------------------------------------------
#   DEBUG
#
#- name: task_name | DEBUG - show loaded variables
#  tags: tag1,tag2,debug
#  debug:
#    msg: 
#      - "{{ var_1 }}"
#      - "{{ var_2 }}"
#      - "{{ var_3 }}"
#      - "{{ var_4 }}"


#-----------------------------------------------------
#   pre_tasks
#


#-----------------------------------------------------
#   Main
#
- name: system setup | package cleanup | remove unneeded packages (debian, ubuntu, etc)
  tags: software,cleanup,packages,system,settings
  package:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
      - nano
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]


#-----------------------------------------------------
#   post_tasks
#

- name: Reboot 
  tags: software,packages,system,settings
  ansible.builtin.reboot:
    msg: "Rebooting "
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: package_install.changed

#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#


