---
######################################################
#
#     Base config Main
#
######################################################
# README:
#
#

#-----------------------------------------------------
#   variablen
#
#- name: task_name | load variables 
#  tags: tag1,tag2
#  set_fact:
#    var_1: 
#    var_2: 
#    var_3: "{{ beispiel_variable }}"
#    var_4: 

#-----------------------------------------------------
#   DEBUG
#
#- name: task_name | DEBUG - show loaded variables
#  tags: tag1,tag2,debug
#  debug:
#    msg: 
#      - "{{ var_1 }}"
#      - "{{ var_2 }}"
#      - "{{ var_3 }}"
#      - "{{ var_4 }}"


#-----------------------------------------------------
#   pre_tasks
#
- name: main | "load OS-spezific variables"
  tags: base,vars
  ansible.builtin.include_vars:
    file: "all.yml"

- name: main | "load OS-spezific variables"
  tags: base,vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: Update and upgrade package packages
  tags: update
  package:
    update_cache: true
    upgrade: true
  become: true



#-----------------------------------------------------
#   Main
#

- block:
  # setup ansible environment
  - import_tasks: system-setup/ansible_setup.yml

  # Install software
  - import_tasks: software/packages_base.yml

  # Perform remaining import_tasks
  - import_tasks: system-setup/clock.yml
  - import_tasks: system-setup/cron.yml
  - import_tasks: system-setup/locale.yml
  - import_tasks: system-setup/logging.yml
  - import_tasks: system-setup/ssh.yml

  #Erstellen von Usern
  - import_tasks: users/architect_user.yml
  - import_tasks: users/main_user.yml
  - import_tasks: users/root.yml


    #  - import_tasks: software/dotfiles_architect.yml
    #- import_tasks: software/packages_cleanup.yml

#-----------------------------------------------------
#   post_tasks
#


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#


