---
######################################################
#
#     Base config Main
#
######################################################
# README:
#
#

#-----------------------------------------------------
#   variablen
#
#- name: task_name | load variables 
#  tags: tag1,tag2
#  set_fact:
#    var_1: 
#    var_2: 
#    var_3: "{{ beispiel_variable }}"
#    var_4: 

#-----------------------------------------------------
#   DEBUG
#
#- name: task_name | DEBUG - show loaded variables
#  tags: tag1,tag2,debug
#  debug:
#    msg: 
#      - "{{ var_1 }}"
#      - "{{ var_2 }}"
#      - "{{ var_3 }}"
#      - "{{ var_4 }}"


#-----------------------------------------------------
#   pre_tasks
#


#-----------------------------------------------------
#   Main
#
- name: main | "load OS-spezific variables"
  tags: base,vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution }}.yml"

#-----------------------------------------------------
#   post_tasks
#


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#


